apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: stable
  namespace: flux-system
spec:
  interval: 30m
  url: https://charts.helm.sh/stable
# this is to be deprecated please use other helm repo once the charts have been moved
