apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: nginx
  namespace: dev
spec:
  interval: 5m0s
  path: ./myapp/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
