# for accessing cluster wide resources
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cluster-admin
  namespace: rbac-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin-rolebinding
  namespace: rbac-system
subjects:
- kind: ServiceAccount
  name: cluster-admin
  namespace: rbac-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
