apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: appmesh-controller
  namespace: appmesh-system
spec:
  releaseName: appmesh
  chart:
    spec:
      chart: appmesh-controller
      sourceRef:
        kind: HelmRepository
        name: eks
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: 3
  values:
    serviceAccount:
      create: false
      name: appmesh-controller # this is created on the IRSA when doing eksctl create -f
