---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  interval: 1m
  dependsOn:
    - name: cluster-addons
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenants
  prune: true
  validation: client
---
