
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: security-system
spec:
  releaseName: external-secrets
  chart:
    spec:
      chart: kubernetes-external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values: {}
