apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  releaseName: gatekeeper
  chart:
    spec:
      chart: gatekeeper
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    createNamespace: true
