# weave-scope
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: weave-scope
  namespace: kube-system
spec:
  releaseName: weave-scope
  chart:
    spec:
      chart: stable
      sourceRef:
        kind: HelmRepository
        name: weave-scope
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values: {}
