apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: hello-service-password-credentials
spec:
  backendType: secretsManager
  # optional: specify region
  region: us-west-2
  data:
    - key: hello-service/credentials
      name: password
      property: password
