apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: init-cluster-debug
  region: eu-central-1
  version: "1.18"

nodeGroups:
  - name: ng-mesh-01
    instanceType: m5.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    iam:
      withAddonPolicies:
        albIngress: true
        appMesh: true
        xRay: true
        cloudWatch: true

vpc:
  #autoAllocateIPv6: true #This fails to delete
  # disable public access to endpoint and only allow private access
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  nat:
    gateway: HighlyAvailable # other options: Disable, Single (defaul

cloudWatch:
  clusterLogging:
    # enable specific types of cluster control plane logs
    enableTypes: ["audit", "authenticator", "controllerManager", "scheduler", "api"]
    # all supported types: "api", "audit", "authenticator", "controllerManager", "scheduler"
    # supported special values: "*" and "all"
