name: lint-scan-analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: kubeval
        env:
          KUBE_VER: "1.18.0"
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.18.2
          kubeval: 0.15.0
          command: |
            kubeval --strict --ignore-missing-schemas --kubernetes-version ${KUBE_VER} -d clusters,infrastructure --ignored-filename-patterns kustomization.yaml

  lint:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: kube-lint
        id: kube-lint
        uses: stackrox/kube-linter-action@v1
        with:
          directory: .
          #config: .kube-linter/config.yaml

  analyze:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./
          quiet: true 
          framework: kubernetes
          output_format: github_failed_only
