name: validate-lint-scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: kubeval
        env:
          KUBE_VER: "1.18.0"
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.18.2
          kubeval: 0.15.0
          command: |
            kubeval --strict --ignore-missing-schemas --kubernetes-version ${KUBE_VER} -d clusters,infrastructure --ignored-filename-patterns kustomization.yaml

  lint:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: kube-lint
        id: kube-lint
        uses: stackrox/kube-linter-action@v1
        with:
          directory: .
          config: .kube-linter/remove-default-checks.yaml

  scan:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: download-trivy-in-cache
        run: docker pull aquasec/trivy:0.15.0 
      
      - name: get-all-image
        run: mkdir -p /tmp/.cache && find . -name *.yaml -type f -exec cat {} + | grep -E "image\:" | awk '{print $2}' > /tmp/.cache/images
      
      - name: run-scanner
        run: for image in $(cat /tmp/.cache/images); do echo "$image" && docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/tmp/.cache/ $image ; done
