name: lint-scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: kube-lint
        id: kube-lint
        uses: stackrox/kube-linter-action@v1
        with:
          directory: .
          #config: .kube-linter/config.yaml
